services:
  test:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ports:
      - "7777:8888"
      - "0064:0064"
      - "0256:0256"
      - "2121:2121"
      - "0687:7860"
      - "1235:22"
    volumes:
      - /mnt/lv_data/defilippis/:/opt/data/