services:
  test:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ports:
      - "12345:8888"
      - "0064:0064"
      - "0256:0256"
      - "2121:2121"
      - "0687:7860"
      - "1235:22"
    volumes:
      - /mnt/lv_data/defilippis/:/home/jovyan/work
      #- /mnt/lv_data/defilippis/:/opt/data
    user: root           # specify user to ensure permissions
    
    environment:
      - USERNAME=Iknos2023
      - PASSWORD=!Kn0s2023@#
    entrypoint: >
      sh -c "echo '${USERNAME}:${PASSWORD}' | chpasswd && 
             chmod -R ugo+rw /mnt/lv_data/defilippis/ && 
             while true; do sleep 1000; done" 
    user: root  # specify user to ensure permissions
