name: env_name
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter

  - pip:
    - pandas
    - numpy
    - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118


